const ButtonsText = {
  REPORT: "ENTREGAR RELATÓRIO",
  ADD_VISITOR: "ADICIONAR VISITANTE",
  REGISTER: "CADASTRAR",
  CONFIRM: "CONFIRMAR",
  ENTER: "ENTRAR",
  CANCEL: "CANCELAR",
  SAVE_INFORMATION: "SALVAR INFORMAÇÃO",
  APPROVE: "APROVAR",
  REJECT: "REJEITAR",
};

export default ButtonsText;
