const MenuNavigation = {
  DATA: "DADOS",
  NETWORK: "REDES",
  USERS: "USUÁRIOS",
  MEMBERS: "MEMBROS",
  DETAILS: "DETALHES",
  REGISTER: "CADASTRAR",
  VISITORS: "VISITANTES",
  // PENDING: "AGUARDANDO APROVAÇÃO",
  REGISTER_USERS: "CADASTRAR USUÁRIO",
  REGISTER_MEMBERS: "CADASTRAR MEMBRO",
};

export default MenuNavigation;
